package com.project.entities;
// Generated Apr 21, 2023, 8:44:48 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountCouponId generated by hbm2java
 */
@Embeddable
public class AccountCouponId implements java.io.Serializable {

	private int couponId;
	private int accountId;

	public AccountCouponId() {
	}

	public AccountCouponId(int couponId, int accountId) {
		this.couponId = couponId;
		this.accountId = accountId;
	}

	@Column(name = "coupon_id", nullable = false)
	public int getCouponId() {
		return this.couponId;
	}

	public void setCouponId(int couponId) {
		this.couponId = couponId;
	}

	@Column(name = "account_id", nullable = false)
	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountCouponId))
			return false;
		AccountCouponId castOther = (AccountCouponId) other;

		return (this.getCouponId() == castOther.getCouponId()) && (this.getAccountId() == castOther.getAccountId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCouponId();
		result = 37 * result + this.getAccountId();
		return result;
	}

}
