package com.project.entities;
// Generated Apr 21, 2023, 8:44:48 PM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Brand generated by hbm2java
 */
@Entity
@Table(name = "Brand")
public class Brand implements java.io.Serializable {

	private Integer brandId;
	private Serializable brandName;
	private Set<Product> products = new HashSet<Product>(0);

	public Brand() {
	}

	public Brand(Serializable brandName) {
		this.brandName = brandName;
	}

	public Brand(Serializable brandName, Set<Product> products) {
		this.brandName = brandName;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "brand_id", unique = true, nullable = false)
	public Integer getBrandId() {
		return this.brandId;
	}

	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	@Column(name = "brand_name", nullable = false)
	public Serializable getBrandName() {
		return this.brandName;
	}

	public void setBrandName(Serializable brandName) {
		this.brandName = brandName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brand")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
