package com.project.entities;
// Generated Apr 21, 2023, 8:44:48 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "Cart")
public class Cart implements java.io.Serializable {

	private Integer cartId;
	private Account account;
	private Date createdAt;
	private Date updatedAt;
	private CartDetail cartDetail;

	public Cart() {
	}

	public Cart(Account account, Date createdAt, Date updatedAt) {
		this.account = account;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Cart(Account account, Date createdAt, Date updatedAt, CartDetail cartDetail) {
		this.account = account;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.cartDetail = cartDetail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cart_id", unique = true, nullable = false)
	public Integer getCartId() {
		return this.cartId;
	}

	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 23)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "cart")
	public CartDetail getCartDetail() {
		return this.cartDetail;
	}

	public void setCartDetail(CartDetail cartDetail) {
		this.cartDetail = cartDetail;
	}

}
