package com.project.entities;
// Generated Apr 21, 2023, 8:44:48 PM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Coupon generated by hbm2java
 */
@Entity
@Table(name = "Coupon")
public class Coupon implements java.io.Serializable {

	private Integer couponId;
	private CouponType couponType;
	private String couponName;
	private int discount;
	private Serializable description;
	private Date createdAt;
	private Date expiredAt;
	private Set<AccountCoupon> accountCoupons = new HashSet<AccountCoupon>(0);
	private Set<Order> orders = new HashSet<Order>(0);

	public Coupon() {
	}

	public Coupon(CouponType couponType, String couponName, int discount, Date createdAt, Date expiredAt) {
		this.couponType = couponType;
		this.couponName = couponName;
		this.discount = discount;
		this.createdAt = createdAt;
		this.expiredAt = expiredAt;
	}

	public Coupon(CouponType couponType, String couponName, int discount, Serializable description, Date createdAt,
			Date expiredAt, Set<AccountCoupon> accountCoupons, Set<Order> orders) {
		this.couponType = couponType;
		this.couponName = couponName;
		this.discount = discount;
		this.description = description;
		this.createdAt = createdAt;
		this.expiredAt = expiredAt;
		this.accountCoupons = accountCoupons;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "coupon_id", unique = true, nullable = false)
	public Integer getCouponId() {
		return this.couponId;
	}

	public void setCouponId(Integer couponId) {
		this.couponId = couponId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_type_id", nullable = false)
	public CouponType getCouponType() {
		return this.couponType;
	}

	public void setCouponType(CouponType couponType) {
		this.couponType = couponType;
	}

	@Column(name = "coupon_name", nullable = false, length = 200)
	public String getCouponName() {
		return this.couponName;
	}

	public void setCouponName(String couponName) {
		this.couponName = couponName;
	}

	@Column(name = "discount", nullable = false)
	public int getDiscount() {
		return this.discount;
	}

	public void setDiscount(int discount) {
		this.discount = discount;
	}

	@Column(name = "description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expired_at", nullable = false, length = 23)
	public Date getExpiredAt() {
		return this.expiredAt;
	}

	public void setExpiredAt(Date expiredAt) {
		this.expiredAt = expiredAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coupon")
	public Set<AccountCoupon> getAccountCoupons() {
		return this.accountCoupons;
	}

	public void setAccountCoupons(Set<AccountCoupon> accountCoupons) {
		this.accountCoupons = accountCoupons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coupon")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
