package com.project.entities;
// Generated Apr 21, 2023, 8:44:48 PM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InvoiceStatus generated by hbm2java
 */
@Entity
@Table(name = "Invoice_Status")
public class InvoiceStatus implements java.io.Serializable {

	private Integer invoiceStatusId;
	private Serializable statusName;
	private Serializable statusDescription;
	private Set<Invoice> invoices = new HashSet<Invoice>(0);

	public InvoiceStatus() {
	}

	public InvoiceStatus(Serializable statusName, Serializable statusDescription) {
		this.statusName = statusName;
		this.statusDescription = statusDescription;
	}

	public InvoiceStatus(Serializable statusName, Serializable statusDescription, Set<Invoice> invoices) {
		this.statusName = statusName;
		this.statusDescription = statusDescription;
		this.invoices = invoices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "invoice_status_id", unique = true, nullable = false)
	public Integer getInvoiceStatusId() {
		return this.invoiceStatusId;
	}

	public void setInvoiceStatusId(Integer invoiceStatusId) {
		this.invoiceStatusId = invoiceStatusId;
	}

	@Column(name = "status_name", nullable = false)
	public Serializable getStatusName() {
		return this.statusName;
	}

	public void setStatusName(Serializable statusName) {
		this.statusName = statusName;
	}

	@Column(name = "status_description", nullable = false)
	public Serializable getStatusDescription() {
		return this.statusDescription;
	}

	public void setStatusDescription(Serializable statusDescription) {
		this.statusDescription = statusDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoiceStatus")
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

}
