package com.project.entities;
// Generated Apr 22, 2023, 11:44:21 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrderStatus generated by hbm2java
 */
@Entity
@Table(name = "OrderStatus")
public class OrderStatus implements java.io.Serializable {

	private Integer orderStatusId;
	private String statusName;
	private String statusDescription;
	private Set<Order> orders = new HashSet<Order>(0);

	public OrderStatus() {
	}

	public OrderStatus(String statusName, String statusDescription) {
		this.statusName = statusName;
		this.statusDescription = statusDescription;
	}

	public OrderStatus(String statusName, String statusDescription, Set<Order> orders) {
		this.statusName = statusName;
		this.statusDescription = statusDescription;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_status_id", unique = true, nullable = false)
	public Integer getOrderStatusId() {
		return this.orderStatusId;
	}

	public void setOrderStatusId(Integer orderStatusId) {
		this.orderStatusId = orderStatusId;
	}

	@Column(name = "status_name", nullable = false)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@Column(name = "status_description", nullable = false)
	public String getStatusDescription() {
		return this.statusDescription;
	}

	public void setStatusDescription(String statusDescription) {
		this.statusDescription = statusDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderStatus")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
