package com.project.entities;
// Generated Apr 21, 2023, 8:44:48 PM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrderStatus generated by hbm2java
 */
@Entity
@Table(name = "Order_Status")
public class OrderStatus implements java.io.Serializable {

	private Integer orderStatusId;
	private Serializable statusName;
	private Serializable statusDescription;
	private Set<Order> orders = new HashSet<Order>(0);

	public OrderStatus() {
	}

	public OrderStatus(Serializable statusName, Serializable statusDescription) {
		this.statusName = statusName;
		this.statusDescription = statusDescription;
	}

	public OrderStatus(Serializable statusName, Serializable statusDescription, Set<Order> orders) {
		this.statusName = statusName;
		this.statusDescription = statusDescription;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_status_id", unique = true, nullable = false)
	public Integer getOrderStatusId() {
		return this.orderStatusId;
	}

	public void setOrderStatusId(Integer orderStatusId) {
		this.orderStatusId = orderStatusId;
	}

	@Column(name = "status_name", nullable = false)
	public Serializable getStatusName() {
		return this.statusName;
	}

	public void setStatusName(Serializable statusName) {
		this.statusName = statusName;
	}

	@Column(name = "status_description", nullable = false)
	public Serializable getStatusDescription() {
		return this.statusDescription;
	}

	public void setStatusDescription(Serializable statusDescription) {
		this.statusDescription = statusDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderStatus")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
