package com.project.entities;
// Generated Apr 21, 2023, 8:44:48 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductSizeId generated by hbm2java
 */
@Embeddable
public class ProductSizeId implements java.io.Serializable {

	private int productId;
	private int sizeId;

	public ProductSizeId() {
	}

	public ProductSizeId(int productId, int sizeId) {
		this.productId = productId;
		this.sizeId = sizeId;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "size_id", nullable = false)
	public int getSizeId() {
		return this.sizeId;
	}

	public void setSizeId(int sizeId) {
		this.sizeId = sizeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductSizeId))
			return false;
		ProductSizeId castOther = (ProductSizeId) other;

		return (this.getProductId() == castOther.getProductId()) && (this.getSizeId() == castOther.getSizeId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getSizeId();
		return result;
	}

}
