package com.project.entities;
// Generated Apr 22, 2023, 11:44:21 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductSize generated by hbm2java
 */
@Entity
@Table(name = "ProductSize")
public class ProductSize implements java.io.Serializable {

	private Integer sizeId;
	private int sizeName;
	private Set<ProductVariant> productVariants = new HashSet<ProductVariant>(0);

	public ProductSize() {
	}

	public ProductSize(int sizeName) {
		this.sizeName = sizeName;
	}

	public ProductSize(int sizeName, Set<ProductVariant> productVariants) {
		this.sizeName = sizeName;
		this.productVariants = productVariants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "size_id", unique = true, nullable = false)
	public Integer getSizeId() {
		return this.sizeId;
	}

	public void setSizeId(Integer sizeId) {
		this.sizeId = sizeId;
	}

	@Column(name = "size_name", nullable = false)
	public int getSizeName() {
		return this.sizeName;
	}

	public void setSizeName(int sizeName) {
		this.sizeName = sizeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productSize")
	public Set<ProductVariant> getProductVariants() {
		return this.productVariants;
	}

	public void setProductVariants(Set<ProductVariant> productVariants) {
		this.productVariants = productVariants;
	}

}
