package com.project.entities;
// Generated Apr 22, 2023, 11:44:21 AM by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductColor generated by hbm2java
 */
@Entity
@Table(name = "ProductColor")
public class ProductColor implements java.io.Serializable {

	private Integer colorId;
	private String colorName;
	private Set<ProductVariant> productVariants = new HashSet<ProductVariant>(0);

	public ProductColor() {
	}

	public ProductColor(String colorName) {
		this.colorName = colorName;
	}

	public ProductColor(String colorName, Set<ProductVariant> productVariants) {
		this.colorName = colorName;
		this.productVariants = productVariants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "color_id", unique = true, nullable = false)
	public Integer getColorId() {
		return this.colorId;
	}

	public void setColorId(Integer colorId) {
		this.colorId = colorId;
	}

	@Column(name = "color_name", nullable = false)
	public Serializable getColorName() {
		return this.colorName;
	}

	public void setColorName(String colorName) {
		this.colorName = colorName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productColor")
	public Set<ProductVariant> getProductVariants() {
		return this.productVariants;
	}

	public void setProductVariants(Set<ProductVariant> productVariants) {
		this.productVariants = productVariants;
	}

}
