package com.project.entities;
// Generated Apr 21, 2023, 8:44:48 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductImage generated by hbm2java
 */
@Entity
@Table(name = "Product_Image")
public class ProductImage implements java.io.Serializable {

	private Integer productImageId;
	private Product product;
	private String imagePath;

	public ProductImage() {
	}

	public ProductImage(Product product, String imagePath) {
		this.product = product;
		this.imagePath = imagePath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "product_image_id", unique = true, nullable = false)
	public Integer getProductImageId() {
		return this.productImageId;
	}

	public void setProductImageId(Integer productImageId) {
		this.productImageId = productImageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "image_path", nullable = false, length = 200)
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

}
