package com.project.models;
// Generated Apr 22, 2023, 11:44:21 AM by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AccountCoupon generated by hbm2java
 */
@Entity
@Table(name = "AccountCoupon")
public class AccountCoupon implements java.io.Serializable {

	private AccountCouponId id;
	private Account account;
	private Coupon coupon;
	private boolean isUsed;

	public AccountCoupon() {
	}

	public AccountCoupon(AccountCouponId id, Account account, Coupon coupon, boolean isUsed) {
		this.id = id;
		this.account = account;
		this.coupon = coupon;
		this.isUsed = isUsed;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "couponId", column = @Column(name = "coupon_id", nullable = false)),
			@AttributeOverride(name = "accountId", column = @Column(name = "account_id", nullable = false)) })
	public AccountCouponId getId() {
		return this.id;
	}

	public void setId(AccountCouponId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false, insertable = false, updatable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coupon_id", nullable = false, insertable = false, updatable = false)
	public Coupon getCoupon() {
		return this.coupon;
	}

	public void setCoupon(Coupon coupon) {
		this.coupon = coupon;
	}

	@Column(name = "is_used", nullable = false)
	public boolean isIsUsed() {
		return this.isUsed;
	}

	public void setIsUsed(boolean isUsed) {
		this.isUsed = isUsed;
	}

}
