package com.project.models;
// Generated Apr 22, 2023, 11:44:21 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InvoiceStatus generated by hbm2java
 */
@Entity
@Table(name = "InvoiceStatus")
public class InvoiceStatus implements java.io.Serializable {

	private Integer invoiceStatusId;
	private String statusName;
	private String statusDescription;
	private Set<Invoice> invoices = new HashSet<Invoice>(0);

	public InvoiceStatus() {
	}

	public InvoiceStatus(String statusName, String statusDescription) {
		this.statusName = statusName;
		this.statusDescription = statusDescription;
	}

	public InvoiceStatus(String statusName, String statusDescription, Set<Invoice> invoices) {
		this.statusName = statusName;
		this.statusDescription = statusDescription;
		this.invoices = invoices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "invoice_status_id", unique = true, nullable = false)
	public Integer getInvoiceStatusId() {
		return this.invoiceStatusId;
	}

	public void setInvoiceStatusId(Integer invoiceStatusId) {
		this.invoiceStatusId = invoiceStatusId;
	}

	@Column(name = "status_name", nullable = false)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@Column(name = "status_description", nullable = false)
	public String getStatusDescription() {
		return this.statusDescription;
	}

	public void setStatusDescription(String statusDescription) {
		this.statusDescription = statusDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoiceStatus")
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

}
