package com.project.models;
// Generated Apr 22, 2023, 11:44:21 AM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductVariant generated by hbm2java
 */
@Entity
@Table(name = "ProductVariant")
public class ProductVariant implements java.io.Serializable {

	private Integer variantId;
	private String color;
	private ProductSize productSize;
	private int quantity;
	private Product product;

	public ProductVariant() {
	}

	public ProductVariant(Product product, String color, ProductSize productSize, int quantity) {
		this.product = product;
		this.color = color;
		this.productSize = productSize;
		this.quantity = quantity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "variant_id", unique = true, nullable = false)
	public Integer getVariantId() {
		return this.variantId;
	}

	public void setVariantId(Integer variantId) {
		this.variantId = variantId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "color", nullable = false, length = 50)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "size_id", nullable = false)
	public ProductSize getProductSize() {
		return this.productSize;
	}

	public void setProductSize(ProductSize productSize) {
		this.productSize = productSize;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
