package com.project.models;
// Generated Apr 22, 2023, 11:44:21 AM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductImage generated by hbm2java
 */
@Entity
@Table(name = "ProductImage")
public class ProductImage implements java.io.Serializable {

	private Integer productImageId;
	private Product product;
	private String imageName;

	public ProductImage() {
	}

	public ProductImage(Product product, String imageName) {
		this.product = product;
		this.imageName = imageName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "product_image_id", unique = true, nullable = false)
	public Integer getProductImageId() {
		return this.productImageId;
	}

	public void setProductImageId(Integer productImageId) {
		this.productImageId = productImageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "image_name", nullable = false, length = 200)
	public String getimageName() {
		return this.imageName;
	}

	public void setimageName(String imageName) {
		this.imageName = imageName;
	}

}
